### PR TITLE
Added bullet menu + more

### PR DESCRIPTION
**Pull request by TubBuddy**
Added bullet menu + alterations to the menus to fit where each menu goes.

### CODE REVIEW

**Comment by TheUnknownCod3r** [comment]
Is this the bugged MagicBullets script also used in Abomination? iirc it had a popup error or something, but we can't avoid it, and it works I guess.

**Comment by TubBuddy** [comment]
yes. I removed the ray gun cuz that one literally crashes the game but others are fine.

**Comment by TheUnknownCod3r** [comment]
I apologise for messing up your fork, Github actually hates me, and I didn't see the third person moved.

**Comment by TheUnknownCod3r** [comment]
I just pushed a rewrite of your code for MagicBullets, it fixes the Popup error, and the self getPlayerCameraPos() is the way its called in the Raw files, so should be more accurate. Seems to work as it should :D

**Pull request merged**
