### PR TITLE
Fixed a few shield names + removed unnecessary hashes 

### PR DESCRIPTION
**Pull request by TubBuddy**
The "zhield_gauntlet_dw" doest work so the hash way is the way for now. 
the only weapons/items are needed are only the Pegasus strike and Matryoskha Dolls, Maybe dynamite for tag in the future? 
I wonder if u can do inf sliding like bo3? 
Also if there is a function that give u all the parts in a map would be cool.

### CODE REVIEW

**Comment by TubBuddy** [comment]
I do know the string name for Pegasus strike i just don't know to to implement it in to the menu i guess there isn't a &giveclientequipment?.
i added back the comment i just thought it wasn't really needed now buuuuut yeah.
zhield works so ill add them right now, the upgrade didn't though.

**Comment by TheUnknownCod3r** [comment]
Its more if someone else wanted to work on it, they know where I got the stringname, also for myself as a reminder the stringnames ARE in the raw files, lol.

There is a function in zm_equipment.gsc, you'd call it as zm_equipment::give(equipment);, but I never did any work with it except looking at nesting dolls, and it didn't work. I'd assume using GiveClientWeapon would work though, like it does for Monkey Bombs.

I'll check my notes for the upgraded shield, but if that works for the default one the upgraded variant will be similar, just like the Attuned Spectral Shield

**Comment by TubBuddy** [comment]
everything is tested.
Giveclientweapon does work but u need the string name for it not the hashes

**Comment by TheUnknownCod3r** [comment]
yeah giveClientWeapon doesn’t work for hashes, I honestly have no idea why, even a function like below doesn’t work.

GiveHashedWeapon(hash)
{
    self giveWeapon(getWeapon(#””+hash));
}

**Comment by TubBuddy** [comment]
Im guessing that its not a weapon? But even then it gave Samantha Box when i used magic_box  so i don't even know anymore lol

**Comment by TheUnknownCod3r** [comment]
I have no bloody idea lol. But if there’s nothing else, I’m happy settling with the hashes for now till someone else figured it out XD

**Comment by TubBuddy** [comment]
Pegasus and Dolls are the only thing left besides the rest of the guns like Zweihander and Rampage etc etc.

**Comment by TheUnknownCod3r** [comment]
So to confirm, so I can do some local testing, is the pegasus strike just pegasus_strike?

**Comment by TubBuddy** [comment]
No its not. You can try if u want but i literally tried everything in the script hashes and it doesnt work.

**Comment by TheUnknownCod3r** [comment]
Ah alright, I’ll see what I can do. I think I’ve at least figured out why the voyage upgraded shield is stupid for applying the effect, so I’ll check that in the morning. I’ll see about Pegasus strike as well, the matryoshka dolls are just weird, I can’t seem to find a valid hash for them at all, which I can normally get.

**Comment by TubBuddy** [comment]
3c0d17bad169557b if for the doll ill do Pegasus later.

**Comment by TheUnknownCod3r** [comment]
The Pegasus strike should be the hash I provided, it’s literally direct from the zm_red gsc files, and it’s in Hashed-3, in the pegasus_strike thing.

**Comment by TubBuddy** [comment]
Weird its  3c0d17bad169557b for me same as dolls... Huh
Capture
?

**Comment by TubBuddy** [comment]
Ok so Pegasus strike works with Hashes the one you provided. That means that the dolls hashes are wrong. So now the only thing left is Dolls.

**Comment by TubBuddy** [comment]
Nevermind... I got the dolls now... Finally!

**Pull request merged**
