### PR TITLE
added all wws upgrades 

### PR DESCRIPTION
**Pull request by TubBuddy**
russians dolls are the only thing that i cant seem to get.

### CODE REVIEW

**Comment by TheUnknownCod3r** [comment]
Just had to slightly fix the PR before merging, as it was broken on my side. Will Merge now, nice work. Im honestly not sure on the stringname or the hash for the matryoshka dolls, but Im looking for it on my side. It'll be in one of the hashed files, not the mapped ones, although i'd at least assume there was a reference in zm_weapons.

**Comment by TubBuddy** [comment]
I do know the hash for it but when i plug it into the MM it doesnt work.
I tried all sorts of commands for it but it still doesnt work. The weirdest thing is i tried to see the name for it and it was blank?

**Comment by TubBuddy** [comment]
I think i got the russian dolls names so i will impliment it today.
I think i have some catalysts functions but i dont know how to call it. Would appreciate if u would send the function to spawn catalysts. Also quick question... Can you manipluate the game into thinking that u completed like 999 contracts? If so u can just use "complete active contracts" and get alot of cases? Just a idea i thew out 👍

**Comment by TheUnknownCod3r** [comment]
I'd assume the Matryoshka dolls would be one of these

		arrayinsert(a_abilities, getweapon(#"hash_34b7eb9fde56bd35"), 0);
		arrayinsert(a_abilities, getweapon(#"incendiary_grenade"), 0);
		arrayinsert(a_abilities, getweapon(#"sticky_grenade"), 0);
		arrayinsert(a_abilities, getweapon(#"proximity_grenade"), 0);
		arrayinsert(a_abilities, getweapon(#"incendiary_fire"), 0);
		arrayinsert(a_abilities, getweapon(#"concussion_grenade"), 0);
		arrayinsert(a_abilities, getweapon(#"flash_grenade"), 0);
		arrayinsert(a_abilities, getweapon(#"emp_grenade"), 0);
		arrayinsert(a_abilities, getweapon(#"cymbal_monkey"), 0);
		arrayinsert(a_abilities, getweapon(#"hash_13fbf1dd07d9cf3e"), 0);
		arrayinsert(a_abilities, getweapon(#"tomahawk_t8"), 0);
		
		But I dont have time to check today

**Comment by TheUnknownCod3r** [comment]
Looking at zm_spawner, zombie_tesla_head_gib is

```
function zombie_tesla_head_gib()
{
	self endon(#"death");
	if(self.animname === "quad_zombie")
	{
		return;
	}
	if(randomint(100) < zombie_utility::function_d2dfacfd(#"tesla_head_gib_chance"))
	{
		wait(randomfloatrange(0.53, 1));
		self zombie_utility::zombie_head_gib();
	}
	else
	{
		zm_net::network_safe_play_fx_on_tag("tesla_death_fx", 2, level._effect[#"tesla_shock_eyes"], self, "J_Eyeball_LE");
	}
}
```

and the other is 

```
function zombie_complete_emerging_into_playable_area()
{
	self.should_turn = 0;
	self.completed_emerging_into_playable_area = 1;
	self.no_powerups = 0;
	self notify(#"completed_emerging_into_playable_area");
	if(isdefined(self.backedupgoal))
	{
		self setgoal(self.backedupgoal);
		self.backedupgoal = undefined;
	}
	else
	{
		self.var_93a62fe = zm_utility::get_closest_valid_player(self.origin, self.ignore_player, 1);
		if(isdefined(self.var_93a62fe) && (!ai::has_behavior_attribute("scripted_mode") || ai::get_behavior_attribute("scripted_mode") !== 1))
		{
			if(isdefined(self.var_93a62fe.last_valid_position))
			{
				self setgoal(self.var_93a62fe.last_valid_position);
			}
			else
			{
				goalpos = getclosestpointonnavmesh(self.var_93a62fe.origin, 100, self getpathfindingradius());
				if(!isdefined(goalpos))
				{
					goalpos = self.origin;
				}
				self setgoal(goalpos);
			}
		}
		else
		{
			self setgoal(self.origin);
		}
	}
	self thread function_1446cbd3();
	self thread zm_utility::update_zone_name();
}
```

Both of these i'd assume would need to be called onto a spawned entity to get it to thread correctly. I took a quick look at how Serious did it for BO3 with spawning Margwa's and Wasps, and that seems to be the correct way to do it.

**Comment by TubBuddy** [comment]
Ahh makes sense.

**Pull request merged**
