### PR TITLE
All Shields Added

### PR DESCRIPTION
**Pull request by TubBuddy**
Removed RayGun For now since we can get a fix.

### CODE REVIEW

**Comment by TheUnknownCod3r** [comment]
So I have several of the normal shield string names, I’m happy to merge it but I’ll be switching them for stringnames anyway. The ray gun I’ll need to test properly when I actually get time, but I agree with removing it if it’s having issues.

**Comment by TubBuddy** [comment]
Sure. Also switching ballistic shield  out for Riot shield will spit out errors left and right, even with changing it to something like "RiotShieldTag" will still spit out errors so bear that in mind.

**Comment by TubBuddy** [comment]
Ok so the ray gun works on Aether maps only. If u use it on Chaos maps it will spit out errors. Just copy and paste the code if ("AO", if "blood" etc etc and it will work.

**Comment by TubBuddy** [comment]
Upgraded ballistic shield does not work on voyage which is weird. As for the other items they are stuck in limbo since idk the name for them. It would be great if there was a code name that you can pull like pulling the hash names for weapons and such.

**Comment by TheUnknownCod3r** [comment]
Didn't get a chance to comment on this before I merged it, ray gun only working on Aether makes sense since its an Aether weapon, I never even thought to test it on Chaos, as I prefer playing Tag. Future note for me to test on all storylines in future, lol. 

As far as I know, you need to dump the Stringtables, which will contain all the unhashed weapon names, I just never got around to it.  on BO3 the stringtables contained challenge data, stat data, weapon data etc, so i'd assume they also contain the same stuff on BO4. Thats probably the fastest way, but Ive not looked at it.

The reason it doesn't work on Voyage is because iirc the Voyage shield name is something like zhield_gauntlet_dw, not the Ballistic shield. It works for now, but it'll probably get changed to the actual shield eventually. The only recommendation I can give you is to scroll the raw files first, since it contains most things not only in hashed but unhashed form. A lot of the WW's seem hashed, but the stringnames are there.

Again, I appreciate the help in keeping stuff updated and tested properly. :)

**Pull request merged**
